services:
  bot:
    build: .
    container_name: emoji_sticker_copy_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
